"""create users, groups, and user_group tables

Revision ID: 3d5c8c88546a
Revises: 2107c8c19b24
Create Date: 2025-08-09 12:41:20.848026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d5c8c88546a'
down_revision: Union[str, Sequence[str], None] = '2107c8c19b24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('group_id', sa.String(), nullable=False),
    sa.Column('group_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_index(op.f('ix_groups_group_id'), 'groups', ['group_id'], unique=False)
    op.create_index(op.f('ix_groups_group_name'), 'groups', ['group_name'], unique=False)
    op.create_table('user_group',
    sa.Column('group_id', sa.String(), nullable=False),
    sa.Column('user_line_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.group_id'], ),
    sa.ForeignKeyConstraint(['user_line_id'], ['users.line_id'], ),
    sa.PrimaryKeyConstraint('group_id', 'user_line_id')
    )
    op.alter_column('users', 'line_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_column('users', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.alter_column('users', 'line_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_table('user_group')
    op.drop_index(op.f('ix_groups_group_name'), table_name='groups')
    op.drop_index(op.f('ix_groups_group_id'), table_name='groups')
    op.drop_table('groups')
    # ### end Alembic commands ###
